name: Deploy

on:
  push:
    branches:
      - e309637

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: HRKU-dfd6524c-b425-45d5-8013-b6bef814c64e
          heroku_app_name: notas-2 #Must be unique in Heroku
          heroku_email: sabenalcazarm@uce.edu.ec